export interface IDocuments {
  length: number
  forEach(arg0: (doc: IDocument) => void): unknown
  documents: IDocument[]

  map(element: (offer: IDocument, index: number) => JSX.Element): any
}

export interface IDocument {
  Commentadminv: string
  abandonne: string
  aemettre: string
  arrivee: string
  auteur: string
  avecagrement: string
  canal: string
  civilitecon: string
  civilitefac: string
  civiliteliv: string
  code: string
  codeappel: string
  codecampagne: string
  codeom: string
  codeplateau: string
  codeprospect: string
  codesv: string
  codesvplateau: string
  codeto: string
  codetoorigine: string
  confirmecat: string
  confirmeto: string
  cpcon: string
  cpfac: string
  cpliv: string
  dateabandonne: string
  datearrivee: string
  dateconfirmecat: string
  dateconfirmeto: string
  datecreation: string
  datefrigo: string
  datefsclient: string
  dategagne: string
  dateimprime: string
  dateperdu: string
  daterecuclient: string
  daterelance: string
  datereportliv: string
  datetranscde: string
  datetransdev: string
  decisionnaire: string
  delailivraison: string
  delaireglement: string
  email: string
  etageliv: string
  fax: string
  fmanu: string
  fsclient: string
  gagne: string
  heurerelance: string
  idcon: string
  idfac: string
  idliv: string
  impannule: string
  imprime: string
  infoclient: string
  infofourfac: string
  infofourliv: string
  infoto: string
  marquemanuel: string
  minuterelance: string
  modelivraison: string
  modereglement: string
  montantremercier: string
  nemissions: string
  newdoc: string
  nom: string
  nomcon: string
  nomfac: string
  nomfichiermail: string
  nomliv: string
  nomtiff: string
  perdu: string
  portht: string
  qualsigfac: string
  recuclient: string
  refsource: string
  remercierle: string
  remercierpar: string
  rue1con: string
  rue1fac: string
  rue1liv: string
  rue2con: string
  rue2fac: string
  rue2liv: string
  sigfac: string
  sstatut: string
  statut: string
  tauxremise: string
  tbht: string
  telcon: string
  telfac: string
  telliv: string
  tht: string
  tnht: string
  transcde: string
  transdev: string
  tttc: string
  ttva: string
  typedoc: string
  typerelance: string
  villecon: string
  villefac: string
  villeliv: string
}
